### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by mitroulias77** [skroutz/greek_stemmer#31]
Ειχαμε ενα προβλημα με τις κωδικοποιησεις:

Traceback (most recent call last):
  File "E:/Python/classification/scripts/nsk_fit.py", line 31, in <module>
    stemmer = gr_stemm.GreekStemmer()
  File "χ\Anaconda3\lib\site-packages\greek_stemmer\__init__.py", line 35, in __init__
    custom_rules = self.load_settings()
  File "χ\Anaconda3\lib\site-packages\greek_stemmer\__init__.py", line 340, in load_settings
    custom_rules = yaml.load(f.read())
  File "χ\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 72: character maps to <undefined>

Το προβλήμα λυνεται ως εξης ( στη περιπτωση μας):
γραμμη 339, file: __init__.py:
os.path.dirname(__file__), 'stemmer.yml'), 'r', encoding="utf8") as f:

**Comment by cmantas** [comment]
Hello.
Can you please elaborate on what this stack trace and error means?*
Seeing a python stack trace on a ruby project seems somewhat peculiar.
